name: Check for secrets
on:
  workflow_dispatch:

permissions:
  actions: read

jobs:
  echo_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Secret
        run: |
          echo "KEY"
          echo ${{ secrets.USER_API_KEY }}
