name: gcp-auth-script
on:
  push:
    branches:
      - ci-testing
      - main
      - release/* #ToDo: add a release branch
  pull_request:
  workflow_dispatch:

jobs:
  activate-vm:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Demos🛎
         uses: actions/checkout@v2
         with:
             path: demos
             persist-credentials: false
             submodules: "recursive"
             fetch-depth: 1

       - name: Install clients
         run: |
           pip install google-api-python-client paramiko

       - name: Start GPU VM
         run: |
           python3 vm_auth.py ${{ secrets.GCP_AUTH }} ${{ secrets.SSH_KEY }}

  run-test:
    needs: activate-vm
    runs-on: self-hosted
    steps:
      - name: Checkout Demos🛎
        uses: actions/checkout@v2
        with:
          path: demos
          persist-credentials: false
          submodules: "recursive"
          fetch-depth: 1

      - name: Run Demo Testing
        run: |
          echo "testing things out!"

  deactivate-vm:
    needs: run-test
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          credentials_json: '${{ secrets.GCP_AUTH }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      - name: 'Stop VM instance'
        run: 'gcloud compute instances stop demos-tests --zone us-central1-a'


